title : Dr Robert Layton
description: 'Data Scientist and Startup Creator'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
